#!/usr/bin/env bash
# build-ollama-image.sh — build a custom Ollama image with OLLAMA_MODEL pre-baked,
# then push to ACR. Idempotent.
#
# Prereqs in /tmp/deploy-vars.sh: ACR_NAME, OLLAMA_MODEL.
set -euo pipefail

: "${ACR_NAME:?}"
: "${OLLAMA_MODEL:?}"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/../../../.." && pwd )"
BUILD_DIR="$REPO_ROOT/sidecar/dev/ollama"

mkdir -p "$BUILD_DIR"
cat > "$BUILD_DIR/Dockerfile" <<DOCKERFILE
# Auto-generated by build-ollama-image.sh
FROM ollama/ollama:latest
ENV OLLAMA_HOST=0.0.0.0:11434

# Pre-pull the model so replicas start with weights on disk.
# This takes 1-5 minutes depending on model size.
RUN ollama serve & \\
    sleep 5 && \\
    ollama pull ${OLLAMA_MODEL} && \\
    pkill ollama || true

EXPOSE 11434
ENTRYPOINT ["ollama", "serve"]
DOCKERFILE

# Tag incorporates the model name for traceability.
TAG=$(echo "$OLLAMA_MODEL" | tr ':.' '-')
IMAGE="${ACR_NAME}.azurecr.io/agent-id-dev/ollama:${TAG}"

echo "Building $IMAGE (baked model: $OLLAMA_MODEL)..."
az acr login --name "$ACR_NAME"
docker buildx build --platform linux/amd64 -t "$IMAGE" --push "$BUILD_DIR"

echo "Pushed: $IMAGE"
echo "export OLLAMA_IMAGE=\"$IMAGE\"" >> "${VARS_FILE:-/tmp/deploy-vars.sh}"
